# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


zeros會產生全部為零的元素，empty會產生極小且接近零但不為零的元素
有時候只是想要快速初始化一個陣列，可使用empty (因不需給定數值，因此速度較快）

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [8]:
# 記得先 Import 正確的套件
import numpy as np

In [17]:
# 參考解答

a = np.random.rand(2, 3)
a = a * 100
print(a)
print(np.array(a, dtype=int))#直接去掉小數

#老師方法 ＃四捨五入
print(a.round())
print(np.round(a))

[[69.33698067 49.59257851 12.24112967]
 [29.3256552  66.50940603 39.96761627]]
[[69 49 12]
 [29 66 39]]
[[69. 50. 12.]
 [29. 67. 40.]]
[[69. 50. 12.]
 [29. 67. 40.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [39]:
m = 20
n = 40
a = np.random.rand(2, 3)
print(a)

[[0.55499795 0.80682943 0.56743796]
 [0.97162424 0.13682211 0.54315308]]


In [40]:
print(a * (n - m) + m)

[[31.09995897 36.1365885  31.34875915]
 [39.43248483 22.73644229 30.8630616 ]]


In [44]:
#老師方法
a = a * (n - m)
print(a)
b = a 
print(b)
print((a - b % 1) + m)

[[11.09995897 16.1365885  11.34875915]
 [19.43248483  2.73644229 10.8630616 ]]
[[11.09995897 16.1365885  11.34875915]
 [19.43248483  2.73644229 10.8630616 ]]
[[31. 36. 31.]
 [39. 22. 30.]]


In [41]:
#正規化方法
def min_max_scale(arr, target_min, target_max):
    arr_min = arr.min()
    arr_max = arr.max()
    if arr_min == arr_max:
        return np.full_like(arr, fill_value=target_min)
    normalized = (arr - arr_min) / (arr_max - arr_min)
    return normalized * (target_max - target_min) + target_min

In [42]:
rescaled = min_max_scale(a, 20, 40)
rescaled

array([[30.01856177, 36.05188317, 30.31659669],
       [40.        , 20.        , 29.7347851 ]])

In [43]:
# 最小最大正規化公式
a_min = a.min()
a_max = a.max()

normalized = (a - a_min) / (a_max - a_min) 
rescaled = normalized * (n - m) + m

print(rescaled)

[[30.01856177 36.05188317 30.31659669]
 [40.         20.         29.7347851 ]]
