# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np

In [4]:
a = np.arange(6)
print(a)

print(a.sum()) 
#only works on Numpy array object
#This is a method of the NumPy array object.

print(np.sum(a)) 
#This is a NumPy function, not tied to a specific array object.
#It works on any array-like object: Python lists, tuples, or NumPy arrays.


print(sum(a)) 
#python內建，不需另外import套件即可使用

[0 1 2 3 4 5]
15
[0 1 2 3 4 5]
15
[0 1 2 3 4 5]
15
[0 1 2 3 4 5]


印出的結果都一樣，沒有不同

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
#正規化就是將元素轉換到0~1之間

In [5]:
A = np.random.random((5, 5))
(A - A.min()) / (A.max() - A.min())

array([[0.60262353, 0.88837714, 0.1934748 , 0.33501937, 0.        ],
       [0.60678978, 0.68823857, 0.02822228, 0.04453711, 1.        ],
       [0.85462174, 0.76819002, 0.40438913, 0.52788101, 0.84855278],
       [0.24461493, 0.3565281 , 0.33546955, 0.39374738, 0.79626922],
       [0.77140698, 0.79753717, 0.40951801, 0.79351767, 0.21927692]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [11]:
vector = np.random.randint(1, 101, size=10)
print(vector)

#vector[(vector.max())]*= -1 #錯誤因為vector.max()回傳值而不是index

# 找出最大值的位置（index）
max_index = np.argmax(vector)

# 將最大值設為 -1
vector[max_index] = -1

print(vector)

[80 87 52 43 28 40 82 93 75 24]
[80 87 52 43 28 40 82 -1 75 24]
