# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [8]:
print(Z)

[[[5 5 3 ... 9 5 9]
  [1 1 1 ... 7 4 4]
  [1 2 5 ... 6 8 3]
  ...
  [5 9 1 ... 4 5 1]
  [4 6 2 ... 3 9 0]
  [1 7 9 ... 9 0 6]]

 [[3 0 3 ... 7 4 4]
  [5 8 0 ... 1 7 4]
  [3 8 1 ... 4 9 8]
  ...
  [8 5 2 ... 4 7 5]
  [4 8 3 ... 8 2 0]
  [3 0 4 ... 3 0 0]]

 [[8 7 0 ... 1 9 4]
  [5 1 2 ... 6 8 5]
  [6 1 2 ... 0 7 5]
  ...
  [3 2 9 ... 3 7 4]
  [5 4 2 ... 8 5 5]
  [6 4 5 ... 1 6 8]]

 ...

 [[7 9 3 ... 2 4 6]
  [7 4 0 ... 4 9 5]
  [9 3 3 ... 4 4 5]
  ...
  [7 4 5 ... 6 8 4]
  [9 9 0 ... 9 5 6]
  [3 8 6 ... 1 2 5]]

 [[2 5 8 ... 4 9 3]
  [2 5 8 ... 7 8 1]
  [0 9 4 ... 3 7 8]
  ...
  [3 9 1 ... 4 5 5]
  [7 1 0 ... 8 0 5]
  [1 6 9 ... 4 7 0]]

 [[2 9 9 ... 5 9 8]
  [6 5 1 ... 9 1 5]
  [8 0 8 ... 5 1 6]
  ...
  [0 8 7 ... 9 9 7]
  [4 8 5 ... 4 6 4]
  [1 4 7 ... 3 4 7]]]


In [6]:
%timeit -n 10 a = 2
for i in np.nditer(Z):
    i=i+1

76.8 ns ± 21.4 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit -n 10 a = 2
for i in Z:
    for j in i:
        for k in j:
            k=k+1

113 ns ± 25.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
%timeit -n 10 a = 2

for i in Z.flat:
    i=i+1

73.8 ns ± 19.4 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [20]:

Z = np.random.randint(0,10,50)
print(Z)


[3 1 8 0 1 2 9 4 0 0 4 8 9 7 2 8 3 1 7 7 5 9 3 0 1 1 5 1 4 3 2 6 1 5 5 8 5
 6 9 1 1 3 2 7 2 6 6 9 4 0]


In [24]:
find_num = np.bincount(Z).argmax()
print(find_num)
np.where(Z==find_num)[0]

1


array([ 1,  4, 17, 24, 25, 27, 32, 39, 40])

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [28]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[9, 1, 0, 2, 2, 1]
[9, 1, 0, 2, 2, 1]
[[1, 0, 8, 2], [0, 7, 3, 4], [0, 8, 1, 0]]
[array([1, 0, 8, 2]), array([0, 7, 3, 4]), array([0, 8, 1, 0])]
[[[1, 9], [3, 3], [2, 9]], [[9, 1], [8, 9], [4, 5]]]
[array([[1, 9],
       [3, 3],
       [2, 9]]), array([[9, 1],
       [8, 9],
       [4, 5]])]


In [29]:
def tolist(x):
    if isinstance(x, np.ndarray): #檢查是否為ndarray
        return [tolist(i) for i in x]#對這一層裡的每個元素 i，都再次呼叫 tolist(i)，這樣就能一層一層往下轉換。
    elif isinstance(x, (list, tuple)):#或是可迭代的list, tuple
        return [tolist(i) for i in x]
    else:
        return x #不是ist or tuple or ndarray的話則回傳元素


In [30]:
print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 1, 0, 2, 2, 1]
[[1, 0, 8, 2], [0, 7, 3, 4], [0, 8, 1, 0]]
[[[1, 9], [3, 3], [2, 9]], [[9, 1], [8, 9], [4, 5]]]
