# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


使用list()的方式只會轉換第一層，tolist()則可以多層轉換

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [13]:
# 記得先 Import 正確的套件
import numpy as np

In [14]:
a = np.random.randint(10, size=6)

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 3 4 7 6 3]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [15]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[4 4 2 0]
 [6 8 0 9]
 [8 0 3 8]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [16]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[2 2]
  [1 2]
  [1 0]]

 [[4 8]
  [1 7]
  [5 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [17]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[0, 1, 8, 7, 0, 6]
[0, 1, 8, 7, 0, 6]


In [18]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[1, 8, 0, 2], [1, 9, 1, 0], [3, 0, 9, 1]]
[array([1, 8, 0, 2]), array([1, 9, 1, 0]), array([3, 0, 9, 1])]


In [19]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[4, 2], [6, 8], [9, 9]], [[6, 6], [5, 6], [1, 4]]]
[array([[4, 2],
       [6, 8],
       [9, 9]]), array([[6, 6],
       [5, 6],
       [1, 4]])]


In [20]:
def tolist(iterable):
    if type(iterable)!=np.ndarray:
        return iterable
    create_list=[]
    for i in iterable:
        create_list.append(tolist(i))
    return create_list

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 1, 8, 7, 0, 6]
[[1, 8, 0, 2], [1, 9, 1, 0], [3, 0, 9, 1]]
[[[4, 2], [6, 8], [9, 9]], [[6, 6], [5, 6], [1, 4]]]
